[Frontend-3] - Adiciona componente de Input
pedroamaral91/simple-dashboard pull request #4
Opened 2020-04-09 21:35 UTC by douglas-cavalcante

2020-04-10 14:24 UTC, pedroamaral91 requested changes
Acho melhor ao invés de deixar escopado componentes de formulários na pasta form, deixar escopado em uma pasta pertinente ao componente, por exemplo:
src/components/inputs/input-text/index.tsx

Na hora de exportar, criar um index.tsx dentro da pasta inputs e exportar todos os componentes como named export. Exemplo:

`index.tsx`:
`export { default as InputText } from './input-text `

2020-04-10 14:24 UTC, pedroamaral91 commented on src/components/form/input-icon/styles.ts
> +  color: ${({ theme }) => theme.semantic.danger};
utilizar a cor do text no tema

2020-04-13 12:11 UTC, wturatti approved these changes

2020-04-13 12:17 UTC, douglas-cavalcante commented on src/components/form/input-icon/styles.ts
> +  color: ${({ theme }) => theme.semantic.danger};
Corrigido

2020-04-13 12:47 UTC, merged