Frontend 5
pedroamaral91/simple-dashboard pull request #5
Opened 2020-04-13 16:45 UTC by douglas-cavalcante

Adiciona o componente de Select

2020-04-13 17:27 UTC, wturatti approved these changes

2020-04-14 00:46 UTC, pedroamaral91 requested changes

2020-04-14 00:46 UTC, pedroamaral91 commented on src/components/select/select-common/index.tsx
> +  const handleOnBlur = useCallback(e => {
variavel sem utilização

2020-04-14 00:46 UTC, pedroamaral91 commented on src/components/select/select-common/index.tsx
> +function CommonSelect({
transformar em const (padronização)

2020-04-14 00:46 UTC, pedroamaral91 commented on src/components/select/select-common/styles.ts
> +  color: ${props => props.theme.semantic.dark};
utilizar cor de texto do tema

2020-04-14 00:46 UTC, pedroamaral91 commented on src/components/select/select-common/styles.ts
> +  color: ${({ theme }) => theme.semantic.danger};
utilizar cor de texto do tema

2020-04-15 00:38 UTC, pedroamaral91 approved these changes

2020-04-15 00:39 UTC, merged